# -*- restclient -*-
#
# This file contains example requests.
# It can be used directly with Emacs restclient plugin.
# See https://github.com/pashky/restclient.el
#

:host = http://127.0.0.1:5000

# Hello, world!
GET :host/

# Get all saved bookmarks
GET :host/api/v1/bookmarks

# Save bookmark
POST :host/api/v1/bookmarks
Content-Type: application/json

{
  "url": "http://github.com/heutagogy/heutagogy-backend",
  "title": "heutagogy/heutagogy-backend",
  "timestamp": "2016-11-19 01:31:15"
}

# Save bookmark (no timestamp)
# This will use current time
POST :host/api/v1/bookmarks
Content-Type: application/json

{
  "url": "http://github.com/heutagogy/heutagogy-backend",
  "title": "heutagogy-backend"
}

# Save bookmark (no title)
# This will use url as a title
POST :host/api/v1/bookmarks
Content-Type: application/json

{
  "url": "https://github.com/heutagogy"
}