# -*- restclient -*-
#
# This file contains example requests.
# It can be used directly with Emacs restclient plugin.
# See https://github.com/pashky/restclient.el
#

:username = "user2"
:password = "pass2"

:host = 127.0.0.1:5000
:url = http://:host

# Get auth token
POST :url/login
Content-Type: application/json

{
  "username": :username,
  "password": :password
}

# Put token ↓↓↓ (use request above)
:token = ???

# Get all saved bookmarks (unauthorized)
GET :url/api/v1/bookmarks

# Get all saved bookmarks (authorized)
GET :url/api/v1/bookmarks
Authorization: JWT :token

# Get all saved bookmarks (bad token)
GET :url/api/v1/bookmarks
Authorization: JWT 42

# Save bookmark
POST :url/api/v1/bookmarks
Authorization: JWT :token
Content-Type: application/json

{
  "url": "http://github.com/heutagogy/heutagogy-backend",
  "title": "heutagogy/heutagogy-backend",
  "timestamp": "2016-11-19 01:31:15"
}

# Save bookmark (no timestamp)
# This will use current UTC time
POST :url/api/v1/bookmarks
Authorization: JWT :token
Content-Type: application/json

{
  "url": "http://github.com/heutagogy/heutagogy-backend",
  "title": "heutagogy-backend"
}

# Save bookmark (no title)
# This will use url as a title
POST :url/api/v1/bookmarks
Authorization: JWT :token
Content-Type: application/json

{
  "url": "https://github.com/heutagogy"
}

